### ISSUE TITLE
The example on the User Guide does not run.

### ISSUE THREAD

**Issue by patxi12** [bounceur/CupCarbon#29]
Exception in thread "Thread-17160" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.LinkedList.checkElementIndex(Unknown Source)
	at java.util.LinkedList.get(Unknown Source)
	at java.util.Collections$SynchronizedList.get(Unknown Source)
	at device.MessageEventList.addMessageEvent(MessageEventList.java:86)
	at device.MultiChannels.addPacketEvent(MultiChannels.java:36)
	at senscript.Command_SEND.sendOperation(Command_SEND.java:356)
	at senscript.Command_SEND.execute(Command_SEND.java:211)
	at senscript.SenScript.executeCommand(SenScript.java:153)
	at device.SensorNode.execute(SensorNode.java:708)
	at simulation.WisenSimulation.start_simulation(WisenSimulation.java:249)
	at simulation.WisenSimulation.simulate(WisenSimulation.java:70)
	at simulation.WisenSimulation.run(WisenSimulation.java:475)
	at java.lang.Thread.run(Unknown Source)

**Comment by bounceur** [comment]
Kindly send your project to bounceur@gmail.com. I will review it and provide you with the necessary solution.
